name: paymob_sdk
description: "A Flutter plugin for integrating Paymob payment sdk, enabling seamless payment processing on Android and iOS."
version: 0.0.1
homepage: https://github.com/ahmedsaleh210/paymob_sdk

environment:
  sdk: ^3.10.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.app.paymob_sdk
        pluginClass: PaymobSdkPlugin
      ios:
        pluginClass: PaymobSdkPlugin
